version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable X-Pack security (for dev environments)
      - xpack.monitoring.collection.enabled=true  # Enable monitoring
      - xpack.profiling.enabled=true  # Enable profiling (if needed)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline  # Mounting pipeline config
    environment:
      - xpack.monitoring.enabled=false  # Disable xpack monitoring for Logstash (adjust if needed)
      - LS_JAVA_OPTS=-Xmx256m -Xms256m   # Java heap size settings for Logstash
    ports:
      - "5044:5044"  # Beats input (default port for Logstash to receive logs from Beats)
      - "5000:5000"  # Logstash TCP input (if you are using a TCP input plugin)
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318"  # OpenTelemetry receiver for OTLP (HTTP)
      - "4317:4317"  # OTLP gRPC

      # - "55680:55680"  # OpenTelemetry gRPC port (optional)
    networks:
      - elastic
    depends_on:
      - elasticsearch
      # - jaeger
      - zipkin
    restart: always
  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: jaeger
  #   ports:
  #     - "6831:6831/udp" # UDP port for Jaeger agent
  #     - "14268:14268" # HTTP port for spans
  #     - "16686:16686" # the jaeger UI 
  #     - "14250:14250"
  #     # - "4317:4317" # the OpenTelemetry collector grpc 
  #     # - "4319:4318"      # Jaeger OTLP HTTP endpoint (Changed to avoid conflict)
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=false
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
  #     - LOG_LEVEL=debug
  #   networks:
  #     - elastic
    # restart: always
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"  # Zipkin UI and collector
    networks:
      - elastic

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge
  
