# receivers:
#   otlp:
#     protocols:
#       http:
#         endpoint: "0.0.0.0:4318"

# exporters:
#   debug:
#     verbosity: detailed
#   prometheus:
#     endpoint: "0.0.0.0:8888"
#   elasticsearch:
#     endpoint: "http://elasticsearch:9200"

# service:
#   pipelines:
#     metrics:
#       receivers: [otlp]
#       exporters: [debug, elasticsearch]

# 

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
processors:
  cumulativetodelta: {}
  filter:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - "jvm.gc.pause"
exporters:
  debug:
    verbosity: detailed
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
  otlp:
    endpoint: "http://localhost:4318"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [cumulativetodelta, filter]
      exporters: [debug, elasticsearch, otlp]