version: "3.8"
services:
  service-discovery-services:
    build: ../service-discovery-services
    ports:
      - "8761:8761"
  configuration-services:
    build: ../configuration-services
    ports:
      - "8088:8088"
    environment:
      EUREKA_URI: http://service-discovery-services:8761/eureka
    depends_on:
      - service-discovery-services
  gateway-services:
    build: ../gateway-services
    ports:
      - "8072:8072"
    environment:
      EUREKA_URI: http://service-discovery-services:8761/eureka
    depends_on:
      - configuration-services
      - service-discovery-services
  user-services:
    build: ../user-services
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql:5432/user_db
      EUREKA_URI: http://service-discovery-services:8761/eureka
    depends_on:
      - postgresql
      - service-discovery-services
      - configuration-services
      # - authentication-services
  product-services:
    build: ../product-services
    ports:
       - "8082:8082"
    environment:
      DATABASE_URL: jdbc:postgresql://postgresql:5432/product_db
      EUREKA_URI: http://service-discovery-services:8761/eureka
    depends_on:
      - postgresql
      - user-services
      - service-discovery-services
      - configuration-services
  postgresql:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
volumes:
  postgres-data:
  mongo-data:
